version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/cs3238-tsuzu/go-wasmi
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...