version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/cs3238-tsuzu/go-wasmi
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Test
          command: go test -v github.com/cs3238-tsuzu/go-wasmi/...
