version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/cs3238-tsuzu/go-wasmi
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: 
          name: Build
          command: go get -v -t -d ./...
      - run: 
          name: Test
          command: go test -v cover -race -coverprofile=./coverage.out ./...
      - run:
          name: Upload to coveralls
          command: |
            go get github.com/mattn/goveralls
            goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN